//
//  NotificationPlanner.swift
//  OffsetKit
//
//  The 64-cap budgeter, per docs/04-ALERTS-NOTIFICATIONS.md §3 — pure and
//  synchronous. Plans ≤ notificationBudget (56) requests; the remaining
//  reserveSlots (8) are left for between-rebuild econ arrivals and ad-hoc
//  requests (04 §3.2 note). The apply step lives in the app target
//  (AlertsStore, 04 §3.4).
//
//  Priority order (spine §4): sooner > criticalAlarm-backed > opens > econ high
//  > closes > killzones > overlaps/remaining.
//

import Foundation

// MARK: - Planner constants (04 PROPOSED ADDITIONS)

nonisolated public let notificationBudget = 56
nonisolated public let reserveSlots = 8
nonisolated public let perDayCap = 16
nonisolated public let coincidenceMergeWindow: TimeInterval = 60

/// UNNotificationCategory / action identifiers (04 §4.3).
nonisolated public enum NotificationCategoryID {
    public static let openMarket = "OPEN_MARKET"
    public static let econEvent = "ECON_EVENT"
}

nonisolated public enum NotificationActionID {
    public static let viewMarket = "VIEW_MARKET"
    public static let muteToday = "MUTE_TODAY"
    public static let muteSeries = "MUTE_SERIES"
}

// MARK: - PlannedNotification (04 §3.1)

nonisolated public struct PlannedNotification: Identifiable, Hashable, Sendable {
    public let id: String            // == MarketEvent.id (merges keep the smallest member id)
    public let fireDate: Date
    public let zoneID: String        // governing IANA zone for trigger components
    public let title: String
    public let body: String
    public let categoryID: String    // OPEN_MARKET | ECON_EVENT
    public let threadID: String      // MarketID.rawValue | "overlap" | "killzones" | "fx" | "econ"
    public let style: AlertStyle     // .standard | .timeSensitive only (never .criticalAlarm)
    public let priorityRank: Int     // 04 §3.2 step 6 rank (budget debugging UI)

    public init(id: String, fireDate: Date, zoneID: String, title: String, body: String,
                categoryID: String, threadID: String, style: AlertStyle, priorityRank: Int) {
        self.id = id
        self.fireDate = fireDate
        self.zoneID = zoneID
        self.title = title
        self.body = body
        self.categoryID = categoryID
        self.threadID = threadID
        self.style = style
        self.priorityRank = priorityRank
    }
}

// MARK: - NotificationPlanner

nonisolated public struct NotificationPlanner: Sendable {

    public init() {}

    /// 04 §3.2, steps 1–8. `calendar` drives the per-day cap grouping and defaults
    /// to `.current` (parameterized to stay pure/testable — 04 §3.2 step 7).
    public func plan(
        events: [MarketEvent],
        rules: [AlertRule],
        now: Date,
        calendar: Calendar = .current
    ) -> [PlannedNotification] {
        let enabledRules = rules.filter(\.enabled)

        // 1–3. MATCH each event; resolve style; hand alarm-backed anchors to the
        //      AlarmKit lane (dropping same-rule leads; other rules' leads survive
        //      at rank 0 — 04 §3.2 steps 1–3).
        var candidates: [Candidate] = []
        var alarmRuleIDsByAnchor: [String: Set<UUID>] = [:]     // anchor idBody → critical rule ids

        for event in events {
            guard let subject = Subject(event: event) else { continue }
            let matches = enabledRules.filter { rule in subject.matches(rule: rule) }
            guard !matches.isEmpty else { continue }
            let style = matches.map(\.style).max(by: { severity($0) < severity($1) }) ?? .standard

            if style == .criticalAlarm, !subject.isLead {
                // Anchor goes to the alarm lane; remember which rules were critical
                // so their generated leads are dropped too (04 §3.2 step 3).
                let criticalRuleIDs = Set(matches.filter { $0.style == .criticalAlarm }.map(\.id))
                alarmRuleIDsByAnchor[subject.anchorBody, default: []].formUnion(criticalRuleIDs)
                continue
            }
            candidates.append(Candidate(event: event, subject: subject, matches: matches, style: style))
        }

        // Drop leads generated by a rule whose anchor was handed to the alarm lane;
        // a lead surviving on an alarm-backed anchor outranks everything (rank 0).
        var working: [Working] = candidates.compactMap { candidate in
            let anchorAlarmRules = alarmRuleIDsByAnchor[candidate.subject.anchorBody] ?? []
            if candidate.subject.isLead {
                let generators = candidate.matches.filter { rule in
                    guard case .before(let minutes) = leadMoment(of: rule, matching: candidate.subject) else {
                        return false
                    }
                    return minutes == candidate.subject.leadMinutes
                }
                let survivingGenerators = generators.filter { !anchorAlarmRules.contains($0.id) }
                guard !survivingGenerators.isEmpty else { return nil }
                let style = survivingGenerators.map(\.style)
                    .max(by: { severity($0) < severity($1) }) ?? .standard
                guard style != .criticalAlarm else { return nil }
                let rank = anchorAlarmRules.isEmpty ? candidate.baseRank : 0
                return Working(candidate: candidate, style: style, rank: rank)
            }
            return Working(candidate: candidate, style: candidate.style, rank: candidate.baseRank)
        }

        // 4. DROP PAST (fireDate ≤ now + 5 s).
        working.removeAll { $0.candidate.event.date <= now.addingTimeInterval(5) }

        // 5. MERGE COINCIDENT (60 s window, same boundary class) — 04 §3.2 step 5.
        working.sort { lhs, rhs in
            if lhs.candidate.event.date != rhs.candidate.event.date {
                return lhs.candidate.event.date < rhs.candidate.event.date
            }
            return lhs.candidate.event.id < rhs.candidate.event.id
        }
        var merged: [Working] = []
        var index = 0
        while index < working.count {
            var group = [working[index]]
            let head = working[index]
            var next = index + 1
            while next < working.count,
                  let headClass = head.candidate.subject.mergeClass,
                  working[next].candidate.subject.mergeClass == headClass,
                  working[next].candidate.event.date.timeIntervalSince(head.candidate.event.date)
                      <= coincidenceMergeWindow {
                group.append(working[next])
                next += 1
            }
            merged.append(group.count == 1 ? head : Working(merging: group))
            index = next
        }

        // 6. RANK — final sort key (fireDate, priorityRank, id).
        merged.sort { lhs, rhs in
            if lhs.candidate.event.date != rhs.candidate.event.date {
                return lhs.candidate.event.date < rhs.candidate.event.date
            }
            if lhs.rank != rhs.rank { return lhs.rank < rhs.rank }
            return lhs.candidate.event.id < rhs.candidate.event.id
        }

        // 7. PER-DAY CAP (16) — drop lowest-priority, largest-id first within a day.
        var kept: [Working] = []
        var perDay: [DayKey: [Working]] = [:]
        for item in merged {
            perDay[DayKey(item.candidate.event.date, in: calendar), default: []].append(item)
        }
        for (_, items) in perDay.sorted(by: { $0.key < $1.key }) {
            let ordered = items.sorted { lhs, rhs in
                if lhs.rank != rhs.rank { return lhs.rank < rhs.rank }
                if lhs.candidate.event.date != rhs.candidate.event.date {
                    return lhs.candidate.event.date < rhs.candidate.event.date
                }
                return lhs.candidate.event.id < rhs.candidate.event.id
            }
            kept.append(contentsOf: ordered.prefix(perDayCap))
        }
        kept.sort { lhs, rhs in
            if lhs.candidate.event.date != rhs.candidate.event.date {
                return lhs.candidate.event.date < rhs.candidate.event.date
            }
            if lhs.rank != rhs.rank { return lhs.rank < rhs.rank }
            return lhs.candidate.event.id < rhs.candidate.event.id
        }

        // 8. FILL — nearest-first budget (56); farther events wait for a later rebuild.
        return kept.prefix(notificationBudget).map { item in
            PlannedNotification(
                id: item.mergedID ?? item.candidate.event.id,
                fireDate: item.candidate.event.date,
                zoneID: item.candidate.subject.zoneID,
                title: item.mergedTitle ?? item.candidate.event.title,
                body: item.candidate.event.subtitle,
                categoryID: item.candidate.subject.categoryID,
                threadID: item.candidate.subject.threadID,
                style: item.style == .criticalAlarm ? .timeSensitive : item.style,
                priorityRank: item.rank
            )
        }
    }

    // MARK: - Matching internals

    private nonisolated func severity(_ style: AlertStyle) -> Int {
        switch style {
        case .standard: 0
        case .timeSensitive: 1
        case .criticalAlarm: 2
        }
    }

    private nonisolated func leadMoment(of rule: AlertRule, matching subject: Subject) -> AlertMoment? {
        rule.moments.first { moment in
            guard case .before(let minutes) = moment else { return false }
            return minutes == subject.leadMinutes
        }
    }

    /// Event → matching subject, derived from MarketEventKind + the 03 §4.1 id
    /// grammar (segment field parsed from the id for market open/close events).
    nonisolated struct Subject {
        let target: TargetShape
        let boundary: Boundary
        let isLead: Bool
        let leadMinutes: Int?
        let anchorBody: String       // id minus kind field — links leads to anchors
        let zoneID: String
        let categoryID: String
        let threadID: String
        let mergeClass: Boundary?    // non-nil only for merge-eligible kinds (04 §3.2.5)
        let baseRankKind: RankKind

        nonisolated enum Boundary: Equatable { case startLike, endLike }
        nonisolated enum RankKind { case open, econ, close, killzone, remaining }

        nonisolated enum TargetShape: Equatable {
            case market(MarketID, SegmentKind)
            case overlap
            case killzone(KillzoneID)
            case fxWeek
            case econ
        }

        nonisolated func matches(rule: AlertRule) -> Bool {
            let targetMatches: Bool = switch (rule.target, target) {
            case (.market(let id, let segment), .market(let eventID, let eventSegment)):
                id == eventID && segment == eventSegment
            case (.overlap, .overlap), (.fxWeek, .fxWeek), (.econ, .econ):
                // Econ impact filtering already happened in the engine (03 §4 step 5);
                // planner-side econ matching is by target shape (04 §3.2 step 1).
                true
            case (.killzone(let id), .killzone(let eventID)):
                id == eventID
            default:
                false
            }
            guard targetMatches else { return false }

            if isLead {
                return rule.moments.contains { moment in
                    guard case .before(let minutes) = moment else { return false }
                    return minutes == leadMinutes
                }
            }
            return boundary == .startLike
                ? rule.moments.contains(.atOpen)
                : rule.moments.contains(.atClose)
        }

        nonisolated init?(event: MarketEvent) {
            let fields = event.id.components(separatedBy: ":")

            func marketSubject(_ market: MarketID?, segmentField: Bool) -> (TargetShape, String, String)? {
                guard let market else { return nil }
                // id: open:market[:segment]:day — segment field present iff != regular
                let segment: SegmentKind
                if segmentField, fields.count == 4, let parsed = SegmentKind(rawValue: fields[2]) {
                    segment = parsed
                } else {
                    segment = .regular
                }
                return (.market(market, segment), market.rawValue, market.rawValue)
            }

            switch event.kind {
            case .open, .close:
                guard let (shape, thread, _) = marketSubject(event.market, segmentField: fields.count == 4) else {
                    return nil
                }
                let isOpen = event.kind == .open
                target = shape
                boundary = isOpen ? .startLike : .endLike
                isLead = false
                leadMinutes = nil
                anchorBody = fields.dropFirst().joined(separator: ":")
                zoneID = Subject.zone(for: event.market)
                categoryID = NotificationCategoryID.openMarket
                threadID = thread
                mergeClass = boundary
                baseRankKind = isOpen ? .open : .close

            case .preOpen(let minutes), .preClose(let minutes):
                let isPre = if case .preOpen = event.kind { true } else { false }
                // id: preOpen-15:subject[:segment]:day  |  preOpen-15:econ:<econID>
                let body = fields.dropFirst().joined(separator: ":")
                if fields.count >= 2, fields[1] == "econ" {
                    target = .econ
                    threadID = "econ"
                    categoryID = NotificationCategoryID.econEvent
                    zoneID = "America/New_York"
                } else if let market = event.market {
                    guard let (shape, thread, _) = marketSubject(market, segmentField: fields.count == 4) else {
                        return nil
                    }
                    target = shape
                    threadID = thread
                    categoryID = NotificationCategoryID.openMarket
                    zoneID = Subject.zone(for: market)
                } else if fields.count >= 2, fields[1] == "fxLondon-fxNewYork" {
                    target = .overlap
                    threadID = "overlap"
                    categoryID = NotificationCategoryID.openMarket
                    zoneID = "America/New_York"
                } else if fields.count >= 2, fields[1] == "fx" {
                    target = .fxWeek
                    threadID = "fx"
                    categoryID = NotificationCategoryID.openMarket
                    zoneID = "America/New_York"
                } else if fields.count >= 2, let killzone = KillzoneID(rawValue: fields[1]) {
                    target = .killzone(killzone)
                    threadID = "killzones"
                    categoryID = NotificationCategoryID.openMarket
                    zoneID = "America/New_York"
                } else {
                    return nil
                }
                boundary = isPre ? .startLike : .endLike
                isLead = true
                leadMinutes = minutes
                anchorBody = body
                mergeClass = nil
                // Leads inherit their ANCHOR's rank (04 §3.2 step 6).
                baseRankKind = switch target {
                case .econ: .econ
                case .killzone: .killzone
                default: isPre ? .open : .close
                }

            case .overlapStart, .overlapEnd:
                let isStart = event.kind == .overlapStart
                target = .overlap
                boundary = isStart ? .startLike : .endLike
                isLead = false
                leadMinutes = nil
                anchorBody = fields.dropFirst().joined(separator: ":")
                zoneID = "America/New_York"
                categoryID = NotificationCategoryID.openMarket
                threadID = "overlap"
                mergeClass = boundary
                baseRankKind = isStart ? .open : .remaining

            case .killzoneStart(let id), .killzoneEnd(let id):
                let isStart = if case .killzoneStart = event.kind { true } else { false }
                target = .killzone(id)
                boundary = isStart ? .startLike : .endLike
                isLead = false
                leadMinutes = nil
                anchorBody = fields.dropFirst().joined(separator: ":")
                zoneID = "America/New_York"
                categoryID = NotificationCategoryID.openMarket
                threadID = "killzones"
                mergeClass = boundary
                baseRankKind = .killzone

            case .weekOpen, .weekClose:
                let isOpen = event.kind == .weekOpen
                target = .fxWeek
                boundary = isOpen ? .startLike : .endLike
                isLead = false
                leadMinutes = nil
                anchorBody = fields.dropFirst().joined(separator: ":")
                zoneID = "America/New_York"
                categoryID = NotificationCategoryID.openMarket
                threadID = "fx"
                mergeClass = boundary
                baseRankKind = isOpen ? .open : .close

            case .econRelease:
                target = .econ
                boundary = .startLike        // "at release" ≙ .atOpen (04 §3.2 step 1)
                isLead = false
                leadMinutes = nil
                anchorBody = event.id        // "econ:<id>" — already kindless for leads
                zoneID = "America/New_York"  // econ display zone (04 §3.1)
                categoryID = NotificationCategoryID.econEvent
                threadID = "econ"
                mergeClass = nil
                baseRankKind = .econ
            }
        }

        private nonisolated static func zone(for market: MarketID?) -> String {
            switch market {
            case .fxSydney: "Australia/Sydney"
            case .fxTokyo: "Asia/Tokyo"
            case .fxLondon, .lse: "Europe/London"
            case .cmeEquity: "America/Chicago"
            case .fxNewYork, .usEquities, .none: "America/New_York"
            }
        }
    }

    private nonisolated struct Candidate {
        let event: MarketEvent
        let subject: Subject
        let matches: [AlertRule]
        let style: AlertStyle

        /// 04 §3.2 step 6 rank; time-sensitive killzone starts count as opens.
        var baseRank: Int {
            switch subject.baseRankKind {
            case .open: 1
            case .econ: 2
            case .close: 3
            case .killzone: style == .timeSensitive ? 1 : 4
            case .remaining: 5
            }
        }
    }

    private nonisolated struct Working {
        let candidate: Candidate
        let style: AlertStyle
        let rank: Int
        let mergedID: String?
        let mergedTitle: String?

        init(candidate: Candidate, style: AlertStyle, rank: Int) {
            self.candidate = candidate
            self.style = style
            self.rank = rank
            self.mergedID = nil
            self.mergedTitle = nil
        }

        /// Merge coincident members (04 §3.2 step 5): earliest fireDate (the group is
        /// date-sorted), combined title, lexicographically smallest id, max severity.
        init(merging group: [Working]) {
            func styleSeverity(_ style: AlertStyle) -> Int {
                switch style {
                case .standard: 0
                case .timeSensitive: 1
                case .criticalAlarm: 2
                }
            }
            let smallestID = group.map(\.candidate.event.id).min() ?? group[0].candidate.event.id
            self.candidate = group[0].candidate          // earliest fireDate carries the payload
            self.style = group.map(\.style).max(by: { styleSeverity($0) < styleSeverity($1) }) ?? .standard
            self.rank = group.map(\.rank).min() ?? 5
            self.mergedID = smallestID
            self.mergedTitle = group.map(\.candidate.event.title).joined(separator: " + ")
        }
    }
}
